TEST_NAME=PR
EXECUTORS=6

MEM_FRACTION=0.6
FRACTION=0.5
DAG_PATH=None


CLASS=com.ibm.crail.benchmarks.Main
JAR=/home/jyeo/sql-benchmarks/target/sql-benchmarks-1.0.jar
ARGS="-t pagerank -gi 10 -i /user/jyeo/data/graphx/twitter"

MEM_OVERHEAD=3g

SLACK=0
PROMOTE=0.0
TEST_TYPE=Nectar
#TEST_TYPE=Spark2.0
MEM_SIZE=30g
DISAGG=0g
PROFILE_TIMEOUT=60
./drdd_runner.sh $TEST_NAME $TEST_TYPE $MEM_SIZE $EXECUTORS $FRACTION $DISAGG $DAG_PATH $CLASS $JAR $MEM_OVERHEAD $SLACK $PROMOTE $PROFILE_TIMEOUT $MEM_FRACTION $ARGS

TEST_TYPE=Spark2.0
#./drdd_runner.sh $TEST_NAME $TEST_TYPE $MEM_SIZE $EXECUTORS $FRACTION $DISAGG $DAG_PATH $CLASS $JAR $MEM_OVERHEAD $SLACK $PROMOTE $PROFILE_TIMEOUT $MEM_FRACTION $ARGS
#./shutdown.sh
