QUERY=q4
SF=1000
SYSTEM=Spark
DAG_PATH=tpcds-q72-dag

# 90gb total memory
AQE=true
BJ_SIZE=10m

EXECUTORS=3
MEM=30g
./tpcds_runner.sh $QUERY $EXECUTORS $MEM $SF $SYSTEM $DAG_PATH $AQE $BJ_SIZE

EXECUTORS=6
MEM=15g
./tpcds_runner.sh $QUERY $EXECUTORS $MEM $SF $SYSTEM $DAG_PATH $AQE $BJ_SIZE

EXECUTORS=10
MEM=9g
./tpcds_runner.sh $QUERY $EXECUTORS $MEM $SF $SYSTEM $DAG_PATH $AQE $BJ_SIZE

EXECUTORS=15
MEM=6g
./tpcds_runner.sh $QUERY $EXECUTORS $MEM $SF $SYSTEM $DAG_PATH $AQE $BJ_SIZE

EXECUTORS=30
MEM=3g
./tpcds_runner.sh $QUERY $EXECUTORS $MEM $SF $SYSTEM $DAG_PATH $AQE $BJ_SIZE

AQE=false

EXECUTORS=3
MEM=30g
./tpcds_runner.sh $QUERY $EXECUTORS $MEM $SF $SYSTEM $DAG_PATH $AQE $BJ_SIZE

EXECUTORS=6
MEM=15g
./tpcds_runner.sh $QUERY $EXECUTORS $MEM $SF $SYSTEM $DAG_PATH $AQE $BJ_SIZE

EXECUTORS=10
MEM=9g
./tpcds_runner.sh $QUERY $EXECUTORS $MEM $SF $SYSTEM $DAG_PATH $AQE $BJ_SIZE

EXECUTORS=15
MEM=6g
./tpcds_runner.sh $QUERY $EXECUTORS $MEM $SF $SYSTEM $DAG_PATH $AQE $BJ_SIZE

EXECUTORS=30
MEM=3g
./tpcds_runner.sh $QUERY $EXECUTORS $MEM $SF $SYSTEM $DAG_PATH $AQE $BJ_SIZE
